-- V3__create_festivales_and_seed.sql
-- Crea tabla 'festivales' y seed inicial (80 filas) con títulos variados

-- 1) Tabla --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS festivales (
                                          id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          titulo        VARCHAR(160)  NOT NULL,
    descripcion   TEXT,
    city          VARCHAR(120)  NOT NULL,
    fecha_inicio  DATE          NOT NULL,
    fecha_fin     DATE          NOT NULL,
    precio_min    DOUBLE PRECISION,
    precio_max    DOUBLE PRECISION,
    CONSTRAINT chk_fechas_validas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT chk_precios_validos CHECK (
                                             precio_max IS NULL OR precio_min IS NULL OR precio_max >= precio_min
                                         )
    );

-- 2) Índices recomendados -----------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_festivales_titulo_lower ON festivales (lower(titulo));
CREATE INDEX IF NOT EXISTS idx_festivales_city         ON festivales (city);
CREATE INDEX IF NOT EXISTS idx_festivales_fecha_inicio ON festivales (fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_festivales_fecha_fin    ON festivales (fecha_fin);
CREATE INDEX IF NOT EXISTS idx_festivales_precio_min_max ON festivales (precio_min, precio_max);

-- 3) Seed de datos (80 registros) ---------------------------------------------
-- Usamos arrays de adjetivos, nombres y sufijos para crear títulos variados.
-- Las combinaciones están “barajadas” con índices diferentes (mod) para evitar repeticiones tempranas.

WITH adjs(a) AS (
    VALUES (ARRAY[
                'Aurora','Neon','Electric','Wild','Hidden','Urban','Coastal','Forest',
            'Highland','Golden','Crimson','Silver','Nocturnal','Desert','Polar','Solar'
                ])
),
     nouns(a) AS (
         VALUES (ARRAY[
                     'Beats','Vibes','Groove','Echoes','Rhythms','Pulse','Waves','Spectrum',
                 'Harmony','Flux','Anthem','Drift','Jam'
                     ])
     ),
     sufs(a) AS (
         VALUES (ARRAY[
                     'Fest','Open Air','Weekender','Live','Sessions','Experience','Gathering',
                 'Summit','Carnival','Fields','Nights'
                     ])
     ),
     cities(a) AS (
         VALUES (ARRAY[
                     'Barcelona','Madrid','Valencia','Sevilla','Bilbao','Zaragoza','Málaga','Granada',
                 'A Coruña','Valladolid','Murcia','Cádiz','Salamanca','Toledo','Pamplona','Santander'
                     ])
     )
INSERT INTO festivales (titulo, descripcion, city, fecha_inicio, fecha_fin, precio_min, precio_max)
SELECT
    -- Título variado: adjetivo + nombre + sufijo (sin repetir patrón a corto plazo)
    ( adjs.a[ ((gs - 1)        % array_length(adjs.a,1)) + 1 ] || ' ' ||
    nouns.a[ (((gs - 1) * 5) % array_length(nouns.a,1)) + 1 ] || ' ' ||
    sufs.a [ (((gs - 1) * 7) % array_length(sufs.a,1))  + 1 ] )::text AS titulo,

  -- Descripción que incluye la ciudad y un número de edición
  ( 'Edición ' || to_char(gs, 'FM00') || ' · ' ||
    cities.a[ (((gs - 1) * 9) % array_length(cities.a,1)) + 1 ] ||
    ' · Música y tecnología' )::text AS descripcion,

  -- Ciudad rotada con patrón independiente
  cities.a[ (((gs - 1) * 9) % array_length(cities.a,1)) + 1 ] AS city,

  -- Fechas: inicio escalonado cada 3 días desde 2025-06-01; duración fija de 3 días
  (DATE '2025-06-01' + (gs * 3))                     AS fecha_inicio,
  (DATE '2025-06-01' + (gs * 3) + 2)                 AS fecha_fin,

  -- Precios: min entre ~45 y ~104; max siempre >= min
  ROUND(45 + ((gs % 50) * 1.20), 2)                  AS precio_min,
  ROUND(45 + ((gs % 50) * 1.20) + 20 + ((gs % 15) * 1.10), 2) AS precio_max
FROM generate_series(1, 80) AS gs
    CROSS JOIN adjs
    CROSS JOIN nouns
    CROSS JOIN sufs
    CROSS JOIN cities;